const { contextBridge, ipcRenderer } = require("electron");

// NOTE:
// In sandboxed preload contexts, requiring local project modules can fail
// depending on Electron runtime constraints. Keep constants inlined.
// <IPC_CHANNELS:START>
// This block is generated by scripts/generate-ipc-channels.cjs. Do not edit manually.
const IPC_CHANNELS = {
  listRecentFiles: "campusdoc:list-recent-files",
  removeRecentMissing: "campusdoc:remove-recent-missing",
  openFileDialog: "campusdoc:open-file-dialog",
  openFileByPath: "campusdoc:open-file-by-path",
  openTxtDialog: "campusdoc:open-txt-dialog",
  openTxtByPath: "campusdoc:open-txt-by-path",
  createUntitled: "campusdoc:create-untitled",
  saveCurrent: "campusdoc:save-current",
  saveAs: "campusdoc:save-as",
  exportDocument: "campusdoc:export-document",
  confirmUnsavedChanges: "campusdoc:confirm-unsaved-changes",
};
// <IPC_CHANNELS:END>

const invoke = (channel, payload = {}) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld("campusDoc", {
  files: {
    listRecentFiles: () => invoke(IPC_CHANNELS.listRecentFiles),
    removeRecentMissing: (paths) => invoke(IPC_CHANNELS.removeRecentMissing, { paths }),
    openFileDialog: () => invoke(IPC_CHANNELS.openFileDialog),
    openFileByPath: (filePath) => invoke(IPC_CHANNELS.openFileByPath, { filePath }),

    // Deprecated aliases for one release
    openTxtDialog: () => invoke(IPC_CHANNELS.openTxtDialog),
    openTxtByPath: (filePath) => invoke(IPC_CHANNELS.openTxtByPath, { filePath }),

    createUntitled: () => invoke(IPC_CHANNELS.createUntitled),
    saveCurrent: (filePath, content, sourceFormat, suggestedName) =>
      invoke(IPC_CHANNELS.saveCurrent, { filePath, content, sourceFormat, suggestedName }),
    saveAs: (content, sourceFormat, suggestedName) =>
      invoke(IPC_CHANNELS.saveAs, { content, sourceFormat, suggestedName }),
    exportDocument: (payload) => invoke(IPC_CHANNELS.exportDocument, payload),
    confirmUnsavedChanges: (title) => invoke(IPC_CHANNELS.confirmUnsavedChanges, { title }),
  },
});
