const { contextBridge, ipcRenderer } = require("electron");

// NOTE:
// In sandboxed preload contexts, requiring local project modules can fail
// depending on Electron runtime constraints. Keep constants inlined.
// <IPC_CHANNELS:START>
// This block is generated by scripts/generate-ipc-channels.cjs. Do not edit manually.
const IPC_CHANNELS = {
  listDocs: "campusdoc:list-docs",
  importTxt: "campusdoc:import-txt",
  createDoc: "campusdoc:create-doc",
  readDoc: "campusdoc:read-doc",
  saveDoc: "campusdoc:save-doc",
  exportTxt: "campusdoc:export-txt",
};
// <IPC_CHANNELS:END>

const invoke = (channel, payload = {}) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld("campusDoc", {
  files: {
    listDocs: () => invoke(IPC_CHANNELS.listDocs),
    importTxt: () => invoke(IPC_CHANNELS.importTxt),
    createDoc: (title) => invoke(IPC_CHANNELS.createDoc, { title }),
    readDoc: (docId) => invoke(IPC_CHANNELS.readDoc, { docId }),
    saveDoc: (docId, content) => invoke(IPC_CHANNELS.saveDoc, { docId, content }),
    exportTxt: (docId) => invoke(IPC_CHANNELS.exportTxt, { docId }),
  },
});
